security:
  providers:
    users_in_memory:
      memory:
        users:
          admin: { password: '$argon2id$v=19$m=65536,t=4,p=1$8C+VtKORXi1RHd6JjliFMg$G45xi6XwkuvgpwxTxJxRK5TvyCtvmfXUdnEYPLdMsmw'}
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: auto
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      provider: users_in_memory
      json_login:
        check_path: /login

  access_control:
   - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
