security:
  providers:
    users:
      entity:
        class: 'App\UserModule\Domain\User\User'
        property: 'email'
  encoders:
    App\UserModule\Domain\User\User:
      algorithm: auto
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      provider: users
      json_login:
        check_path: /login

  access_control:
   - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
